### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by rsertelon** [gxben/aosp-ethernet#1]
Hi,

I'm interested in your project for jelly beans, do you have any roadmap (what's left to do, when will it be finished, will it be proposed to Google, etc.) ? :)

Anyway, this is a nice implementation of Ethernet support, the nicest one I've seen so far!

Cheers,

**Comment by lawrencetg** [comment]
I also very much anticipated.

**Comment by rsertelon** [comment]
Any news?
